### ISSUE TITLE
instaloader.exceptions.LoginRequiredException: --login required to get a profile's followers.

### ISSUE THREAD

**Issue by travisscottvn** [new92/IGFI#40]
succesfully log in Instagram with Firefox, 
installed cookies.py but its not working n give this error

**Comment by new92** [comment]
Hey @travisscottvn well the error message you're getting is a bug in the login process so let me fix it and I'll get back to you

**Comment by travisscottvn** [comment]
> Hey @travisscottvn well the error message you're getting is a bug in the login process so let me fix it and I'll get back to you

thanks for sharing btw

**Comment by new92** [comment]
Hey @travisscottvn I made some changes in the login process can you make a `git pull` and try executing the script again ? If you get any error please contact me again. If everything works fine please mark this issue as closed. 👍
