### ISSUE TITLE
Instabootloader not found

### ISSUE THREAD

**Issue by Mustehsan** [new92/IGFI#41]
im not able to execute "python3 cookies.py" command getting the error below in the screenshot
![image](https://github.com/new92/IGFI/assets/10628922/667a5576-a832-4e71-ab61-cbc11834cbb6)

**Comment by new92** [comment]
Hey @Mustehsan, in order to resolve this error follow these steps:

1. Open CMD
2. Enter this command `cd C:/Users/muste/appdata/local/programs/python/python312/scripts` 
3. Enter: `pip install instaloader`

**Comment by Mustehsan** [comment]
Already installed
![image](https://github.com/new92/IGFI/assets/10628922/6ea1c6e6-1785-4db8-bf92-b31628d0619a)

**Comment by new92** [comment]
Try entering this `pip install instaloader --upgrade`

**Comment by cool56** [comment]
I have the exact same problem.

**Comment by new92** [comment]
@cool56 have you tried running the `pip install instaloader --upgrade` command ?

**Comment by Mustehsan** [comment]
i did and still the same error

**Comment by cool56** [comment]
> @cool56 have you tried running the `pip install instaloader --upgrade` command ? yes

![Screenshot 2023-11-03 150233](https://github.com/new92/IGFI/assets/33340889/1b200d35-f1f1-4e1a-ab9f-391386ac9d1e)

**Comment by new92** [comment]
@Mustehsan ok let me check it and I'll get back to you

**Comment by new92** [comment]
@cool56 I don't think so let me try fix it

**Comment by Mustehsan** [comment]
I created a virtual machine and installed kali Linux on it and it work like a pie in it. (still not working with windows)

**Comment by new92** [comment]
Great ! Glad it worked. That's strange, I'll check again the Windows installation.

**Comment by cool56** [comment]
So it still doesn't work in windows

**Comment by Mustehsan** [comment]
@cool56 not for me you can try it with linux

**Comment by new92** [comment]
@Mustehsan @cool56 I made some changes to IGFI please try again and let me know.

**Comment by new92** [comment]
@Mustehsan @cool56 were you able to resolve the issues ?

**Comment by mediaticamente** [comment]
Hi, I have the same issue too. Windows 10 here.

**Comment by new92** [comment]
Hey @mediaticamente can you send a screenshot of the error you're encountering ?
