### ISSUE TITLE
RROR: Cannot install -r requirements.txt (line 1) and pydantic>=2.4.0 because these package versions have conflicting dependencies.    

### ISSUE THREAD

**Issue by unzurla** [new92/IGFI#44]
![Instagram](https://github.com/new92/IGFI/assets/130161397/12c7a37c-d3d5-481a-b4e5-5dcdedb0312e)

ERROR: Cannot install -r requirements.txt (line 1) and pydantic>=2.4.0 because these package versions have conflicting dependencies.                      
                                                        
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts                 
Instaloader not found.

**Comment by new92** [comment]
@unzurla ok I removed the package which was causing the conflict try cloning and executing it again ?

**Comment by unzurla** [comment]
> @unzurla ok I removed the package which was causing the conflict try cloning and executing it again ?

still doesnt work it shows me thee same error

**Comment by new92** [comment]
Try now maybe. Also don't repeat the installation process instead enter: `git pull`
