### ISSUE TITLE
After I donloaded the Python Script hat should i do

### ISSUE THREAD

**Issue by unzurla** [new92/IGFI#45]
cd V<and the version you want to use. Example: cd V1   Available versions: 1/2/3>
python3 mainV<and the number of the script. Example: python3 mainV1.py>.py

after that i dont have a clue to continue

**Comment by new92** [comment]
Ok then the script is being executed and what you'll need is:

1. `username` ==> Your username
2. `password` ==> Your password

The script is automated so when you enter python3... it will automatically start the script. And then you'll just to enter your credentials and the followers increasing process will start.

**Comment by unzurla** [comment]
but after i download it i dont see the credentials

**Comment by unzurla** [comment]
[!] Error !                                                                                                                                                                                                                                
[*] Error message ==> The password you entered is incorrect. Please try again.                                                                                                                                                             
[1] Return to menu                                                                                                                                                                                                                         
[2] Exit                                                                                                                                                                                                                                   
[>] Please enter a number (from the above ones):       

my Username and Password is right i dont know why this error popped up

**Comment by new92** [comment]
> but after i download it i dont see the credentials

What do you mean ? Actually the script isn't supposed to show you your credentials you enter them manually.

**Comment by new92** [comment]
> [!] Error ! [*] Error message ==> The password you entered is incorrect. Please try again. [1] Return to menu [2] Exit [>] Please enter a number (from the above ones):
> 
> my Username and Password is right i dont know why this error popped up

Are you trying to increase the followers of an account you created recently ?
