### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by unzurla** [new92/IGFI#46]
I did Cd v3 then python3v3.py

and then filled my insta name and password but this popped up

Instaloader.exceptions.QueryReturnedNotFoundException: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.

**Comment by unzurla** [comment]
File "/usr/local/lib/python3.11/dist-packages/instaloader/instaloadercontext.py", line 382, in get_json                                                                                                                                  
    raise QueryReturnedNotFoundException(error_string) from err                                                                                                                                                                            
instaloader.exceptions.QueryReturnedNotFoundException: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.

**Comment by new92** [comment]
Okay, to resolve this error try executing this:
```bash
cd IGFI/InstagramFollowers
python3 cookies.py
cd V3
python3 mainV3.py
```

**Comment by new92** [comment]
@unzurla were you able to resolve the issue ?

**Comment by kalilinux112** [comment]
File "/home/kalilinux/IGFI/./scripts/igfi.py", line 120, in <module>
    init(autoreset=True)
    ^^^^
NameError: name 'init' is not defined. Did you mean: 'int'?

**Comment by new92** [comment]
@kalilinux112 did you follow the installation process ? Try this command: 
```bash
pip3 install -r requirements.txt
```
