### ISSUE TITLE
Issue with OSX

### ISSUE THREAD

**Issue by hyuma78** [new92/IGFI#48]
I'm using OSX Maverick with python3.11.5 on bash and the script after asking me the questions where I have to reply "yes" doesn't start and I got this error:

Traceback (most recent call last):
  File "/Users/tommy/Desktop/IGFI/scripts/igfi.py", line 659, in <module>
    main(username=str(args.username).strip().lower(), sessionfile=str(args.sessionfile).replace('\\', '/'))
  File "/Users/tommy/Desktop/IGFI/scripts/igfi.py", line 413, in main
    client.user_follow(users[NAMES[j]])
  File "/usr/local/lib/python3.11/site-packages/instagrapi/mixins/user.py", line 735, in user_follow
    assert self.user_id, "Login required"

**Comment by new92** [comment]
Hey @hyuma78. In order to resolve this issue you need to login to your instagram account, complete the verification process and run again IGFI.

**Comment by hyuma78** [comment]
> Hey @hyuma78. In order to resolve this issue you need to login to your instagram account, complete the verification process and run again IGFI.

Yeah I had both Firerox and Brave logged with my Instagram account.

**Comment by new92** [comment]
And you still encountered the 'login_required' error ? Did you execute the `cookies.py` script before `igfi.py` one ?

**Comment by hyuma78** [comment]
Yes, I launched python3 cookies.py and the igfi.py to be sure the cookies were updated. Yes still same issue

**Comment by new92** [comment]
Ok let me fix it and I'll get back to you

**Comment by hyuma78** [comment]
> Ok let me fix it and I'll get back to you

Thank you so much, will wait for your updates!!

**Comment by new92** [comment]
Hey @hyuma78 I made some changes to IGFI and hopefully resolved the issue. Try using it and let me know.

**Comment by hyuma78** [comment]
Different errors now:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/instagrapi/mixins/auth.py", line 391, in login
    logged = self.private_request("accounts/login/", data, login=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 445, in private_request
    raise e
  File "/usr/local/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/instagrapi/mixins/private.py", line 348, in _send_private_request
    raise TwoFactorRequired(**last_json)
instagrapi.exceptions.TwoFactorRequired: Two-factor authentication required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tommy/Desktop/IGFI/./scripts/igfi.py", line 688, in <module>
    main(username=str(args.username).strip().lower(), password=str(args.password).strip(), session=str(args.session).replace('\\', '/')) if args.session is not None else main(username=str(args.username).strip().lower(), password=str(args.password).strip(), session='')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tommy/Desktop/IGFI/./scripts/igfi.py", line 399, in main
    login = client.login(username, password)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/instagrapi/mixins/auth.py", line 397, in login
    raise TwoFactorRequired(f'{e} (you did not provide verification_code for login method)')
instagrapi.exceptions.TwoFactorRequired: Two-factor authentication required (you did not provide verification_code for login method)
```

**Comment by new92** [comment]
@hyuma78 oh I see the issue, try using IGFI with an account that doesn't have 2FA (two factor authentication) enabled. Or disable the 2FA in the current one.

**Comment by hyuma78** [comment]
Ok, I disabled the 2FA and scrips started to following a list of VIP likes Ronaldo, Dua Lipa etc... and at the end unfollowing all of them and then restart the loop. should it work like this? With a series of following and unfollowing?

**Comment by new92** [comment]
Yes that's the process and the goal. Check [this discussion to get your answer](https://github.com/new92/IGFI/discussions/22#discussioncomment-6264613)

**Comment by hyuma78** [comment]
That's incredibile.. there are people in the world that follow the new followers of vip/celebrities for what purpose?!?

**Comment by new92** [comment]
Maybe they're using the "follow for follow back method" maybe they're just following random people who knows ? 🤷‍♂️ The important part is that the users of IGFI are gaining followers. 👍

**Comment by hyuma78** [comment]
Yeah, we live in crazy world! Thanks for the support!

**Comment by new92** [comment]
And that's just a part of it 😅, you're very welcome ! If you need any other assistance don't hesitate to contact me.
