### ISSUE TITLE
Session file not found !

### ISSUE THREAD

**Issue by cumody** [new92/IGFI#51]
**what is the session file and how can i make it**

**Comment by new92** [comment]
Hey there, to answer your first question, you can find your answer [here](https://filext.com/file-extension/SESSION). To generate it simply enter the command:
`python3 cookies.py`. This will return a path to the generated session file, so copy it and run the following command: `python3 igfi.py -u <your_username> -p <your_password> --session <paste the path here>`. But I would sugget you to follow the [installation steps](https://github.com/new92/IGFI?tab=readme-ov-file#installation-). If you have any other questions feel free to comment them in the current issue.👍
