### ISSUE TITLE
Cookie Import Failed

### ISSUE THREAD

**Issue by brxndonroux** [new92/IGFI#54]
I get an error when running cookies.py

![image](https://github.com/new92/IGFI/assets/103594572/3a070af6-0bd3-4d1f-a1fd-98bda3514d7d)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: Browser and Windows latest versions

I have Firefox installed and it looks like theres no session file created.

**Comment by new92** [comment]
Hey @brxndonroux did you login to your account on Insta via Firefox before executing IGFI ?

**Comment by brxndonroux** [comment]
No i didnt log in thank you and yes it was automatically
