### ISSUE TITLE
Imaginary directory

### ISSUE THREAD

**Issue by piggyza** [new92/IGFI#59]
**Describe the bug**
Where this imaginary Directory Path you speak of. for the session, Ive added The mozilla Profile it creates a session json file and still says doesn't exists on windows 11?

**Comment by new92** [comment]
Hey @piggyza are you encountering an error ? If so, can you provide a screenshot ? If the session file doesn't appear make sure you follow the [installation instructions](https://github.com/new92/IGFI?tab=readme-ov-file#installation-). Also make sure to be logged in to your account on Instagram from Firefox before running IGFI and have the Firefox browser installed. Finally, verify that Python is configured correctly and you've installed a compatible with the script version (Python3.X >). To make that verification you can simply enter the command:
```bash
python --version
```
