### ISSUE TITLE
i think im dumb

### ISSUE THREAD

**Issue by flashbackboi** [new92/IGFI#60]
**Desktop (please complete the following information):**
 - firefox[e.g. chrome, safari]
 - Version latest [e.g. 22]
![image](https://github.com/new92/IGFI/assets/146621020/5a93858a-2274-4336-9792-6e65a3a7476b)

**Comment by flashbackboi** [comment]
pls help me

**Comment by new92** [comment]
Hey @flashbackboi make sure you are logged in to your Instagram account via Firefox. And berofe running the 'igfi.py' script run the 'cookies.py' one. 
Reply to this comment if you face any other issue(s).
