### ISSUE TITLE
A Error.

### ISSUE THREAD

**Issue by Mersz** [new92/IGFI#62]
I create this instagram acc 1 week ago,i got this error after i follow some artists, screenshot is below;
![errr](https://github.com/new92/IGFI/assets/84226837/20001d81-2584-4600-a50c-40b0e50ee247)

**Comment by new92** [comment]
Hey, the error you're encountering is because Instagram flagged your account as bot/spam. But it's only temporarily. What I would suggest is to log in to this account and see if there are any verification steps you need to follow.

**Comment by Mersz** [comment]
Thanks mate,yea there was a verification step 1 days ago i already did that

**Comment by new92** [comment]
Great ! Ok so when you manage to resolve the issue and IGFI works fine without any issues contact me again to close this issue !
